### ISSUE TITLE
Cosmetic bug with Reputation extension

### ISSUE THREAD

**Issue by Galixte** [dmzx/Posting-Buttons#3]
Hi,

i found three cosmetic conflicts with Reputation extension: https://github.com/Pico/phpBB-Reputation-System
- Firstly, when a moderator want to warn a user. On MCP page with title "Warn for specific post", 
  in the part named "REPUTATION POINTS FOR WARNING", in the comment field, i have a lot of "comment" images BBCode from your Posting buttons extension (this image http://www.ezcom-fr.com/ext/dmzx/postingbuttons/styles/all/theme/images/comment.png)
  Example with this screenshot: http://www.ezcom-fr.com/download/file.php?id=75
- Secondly, it's the same situation but an other place. On Viewprofile page "Viewing profile - USERNAME", when i click on Rate user i click on the link named "Rate user", a AJAX popup appears to rate and comment the user (of course always a comment) and again in comment field, i have a lot of "comment" images BBCode from your Posting buttons extension (this image http://www.ezcom-fr.com/ext/dmzx/postingbuttons/styles/all/theme/images/comment.png)
  Example with this screenshot: http://www.ezcom-fr.com/download/file.php?id=76
- third, same situation on viewtopic, the example: http://www.ezcom-fr.com/download/file.php?id=77

For those bugs, the "comment" images BBCode forum your Posting buttons extension are in background in the coment filed. It's not a problem to post the comment but it's not his place to display this image.

**Comment by dmzx** [comment]
Will check it out.

**Comment by Galixte** [comment]
Hi @dmzx,

could you take a look ?

**Comment by dmzx** [comment]
open postingbuttons\styles\all\template\event\posting_editor_buttons_before.html

Find id="comment" change to id="comments"

open postingbuttons\styles\all\theme\postingbuttons.css

Find #comment change to #comments

**Comment by Galixte** [comment]
Thanks !

**Comment by Galixte** [comment]
Hi @dmzx,

maybe you could apply this fix in your extension ?

**Comment by Galixte** [comment]
Bump @dmzx, please.

**Comment by dmzx** [comment]
Done ;)

**Comment by Galixte** [comment]
Thanks !-)
